version: '3'

services:
  gogs:
    image: gogs/gogs
    ports:
      - "10022:22"
      - "80:3000"
    volumes:
      - gogs:/data
    depends_on:
      - postgres

  postgres:
    image: postgres
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  gogs:
  postgres:
