version: '3'

services:
  postgres:
    image: postgres:10.0
    env_file:
      - postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gitea:
    image: gitea/gitea:1.2.3
    volumes:
      - gitea-data:/data
    depends_on:
      - postgres

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "10022:22"
    links:
      - gitea
    volumes:
      - nginx-log:/var/log/app

volumes:
  gitea-data:
  postgres-data:
  nginx-log:
