version: '3'

services:
  postgres:
    image: postgres
    env_file:
      - postgres.env
    volumes:
      - postgres:/var/lib/postgresql/data

  gogs:
    image: gogs/gogs
    volumes:
      - gogs:/data
    depends_on:
      - postgres

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "10022:22"
    links:
      - gogs

volumes:
  gogs:
  postgres:
